apiVersion: v1
kind: Service
metadata:
  name: awair-exporter
spec:
  type: LoadBalancer
  selector:
    app: awair-exporter
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
